import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const analyses = sqliteTable("analyses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  symbol: text("symbol").notNull().unique(),
  name: text("name").notNull(),
  market: text("market", { enum: ["US", "SGX"] }).notNull(),
  currency: text("currency"),
  entityType: text("entity_type", { enum: ["standard", "bank", "insurer", "reit"] }).notNull().default("standard"),
  asOfDate: text("as_of_date"),
  periodLabel: text("period_label").notNull().default("TTM"),
  shareBasis: text("share_basis", { enum: ["basic", "diluted"] }).notNull().default("diluted"),
  accountingBasis: text("accounting_basis", { enum: ["reported", "adjusted"] }).notNull().default("reported"),
  sourceLabel: text("source_label").notNull().default("Manual research input"),
  sourceUrl: text("source_url"),
  priceAtAnalysis: real("price_at_analysis"),
  priceCurrency: text("price_currency"),
  priceAsOf: text("price_as_of"),
  fcf: real("fcf"),
  growthRate: real("growth_rate"),
  terminalGrowth: real("terminal_growth"),
  discountRate: real("discount_rate"),
  cash: real("cash"),
  debt: real("debt"),
  shares: real("shares"),
  normalizedEps: real("normalized_eps"),
  fairPe: real("fair_pe"),
  revenue: real("revenue"),
  fairPs: real("fair_ps"),
  revenueGrowth: real("revenue_growth"),
  epsGrowth: real("eps_growth"),
  roic: real("roic"),
  debtEquity: real("debt_equity"),
  fcfMargin: real("fcf_margin"),
  interestCoverage: real("interest_coverage"),
  shareChange: real("share_change"),
  marginTrend: real("margin_trend"),
  dcfValue: real("dcf_value"),
  earningsValue: real("earnings_value"),
  salesValue: real("sales_value"),
  blendedValue: real("blended_value"),
  coveragePercent: real("coverage_percent").notNull().default(0),
  valuationStatus: text("valuation_status", { enum: ["ready", "blocked", "insufficient"] }).notNull().default("insufficient"),
  valuationMessage: text("valuation_message").notNull().default("Add tagged inputs before calculating."),
  sensitivityJson: text("sensitivity_json").notNull().default("[]"),
  qualityScore: real("quality_score"),
  qualityComplete: integer("quality_complete").notNull().default(0),
  analysisVersion: integer("analysis_version").notNull().default(1),
  notes: text("notes").notNull().default(""),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const analysisVersions = sqliteTable("analysis_versions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  symbol: text("symbol").notNull(),
  version: integer("version").notNull(),
  snapshotJson: text("snapshot_json").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const auditEvents = sqliteTable("audit_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  symbol: text("symbol").notNull(),
  action: text("action", { enum: ["created", "updated", "deleted"] }).notNull(),
  details: text("details").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const quoteCache = sqliteTable("quote_cache", {
  symbol: text("symbol").primaryKey(),
  providerSymbol: text("provider_symbol"),
  name: text("name").notNull(),
  market: text("market", { enum: ["US", "SGX"] }).notNull(),
  currency: text("currency"),
  price: real("price"),
  change: real("change"),
  changePercent: real("change_percent"),
  high: real("high"),
  low: real("low"),
  week52High: real("week_52_high"),
  week52Low: real("week_52_low"),
  marketCap: real("market_cap"),
  marketStatus: text("market_status"),
  asOf: text("as_of"),
  sourceUrl: text("source_url"),
  providerHost: text("provider_host"),
  feedState: text("feed_state", { enum: ["fresh", "stale", "down"] }).notNull().default("fresh"),
  adjustmentStatus: text("adjustment_status", { enum: ["unverified", "manual"] }).notNull().default("unverified"),
  historyJson: text("history_json").notNull().default("[]"),
  fetchedAt: integer("fetched_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const watchlist = sqliteTable("watchlist", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  symbol: text("symbol").notNull().unique(),
  name: text("name").notNull(),
  market: text("market", { enum: ["US", "SGX"] }).notNull(),
  currency: text("currency"),
  targetBelow: real("target_below"),
  targetAbove: real("target_above"),
  latestPrice: real("latest_price"),
  priceAsOf: text("price_as_of"),
  sourceUrl: text("source_url"),
  alertZone: text("alert_zone", { enum: ["below", "above"] }),
  splitFactor: real("split_factor").notNull().default(1),
  dividendAdjustment: real("dividend_adjustment").notNull().default(0),
  adjustmentConfirmed: integer("adjustment_confirmed").notNull().default(0),
  feedState: text("feed_state", { enum: ["fresh", "stale", "down"] }).notNull().default("stale"),
  lastCheckedAt: integer("last_checked_at", { mode: "timestamp_ms" }),
  lastSuccessAt: integer("last_success_at", { mode: "timestamp_ms" }),
  lastError: text("last_error"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const alertEvents = sqliteTable("alert_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  symbol: text("symbol").notNull(),
  kind: text("kind", { enum: ["below", "above"] }).notNull(),
  threshold: real("threshold").notNull(),
  price: real("price").notNull(),
  dedupeKey: text("dedupe_key").notNull().unique(),
  deliveredAt: integer("delivered_at", { mode: "timestamp_ms" }),
  triggeredAt: integer("triggered_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const alertHealth = sqliteTable("alert_health", {
  id: integer("id").primaryKey(),
  scheduleLabel: text("schedule_label").notNull().default("Hourly; market sessions only"),
  deliveryChannel: text("delivery_channel").notNull().default("Muse chat"),
  lastAttemptAt: integer("last_attempt_at", { mode: "timestamp_ms" }),
  lastSuccessAt: integer("last_success_at", { mode: "timestamp_ms" }),
  lastError: text("last_error"),
  lastRefreshed: integer("last_refreshed").notNull().default(0),
});

export const weeklyIdeaRuns = sqliteTable("weekly_idea_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  weekKey: text("week_key").notNull(),
  asOfDate: text("as_of_date"),
  status: text("status", { enum: ["ready", "empty", "partial", "failed"] }).notNull().default("empty"),
  universeCount: integer("universe_count").notNull().default(0),
  quoteCount: integer("quote_count").notNull().default(0),
  eligibleCount: integer("eligible_count").notNull().default(0),
  matchCount: integer("match_count").notNull().default(0),
  errorCount: integer("error_count").notNull().default(0),
  earningsCheckedAt: integer("earnings_checked_at", { mode: "timestamp_ms" }),
  earningsCheckedThrough: text("earnings_checked_through"),
  earningsExcludedCount: integer("earnings_excluded_count").notNull().default(0),
  note: text("note"),
  scannedAt: integer("scanned_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
}, (table) => ({ weekKeyUnique: uniqueIndex("weekly_idea_runs_week_key_unique").on(table.weekKey) }));

export const weeklyIdeas = sqliteTable("weekly_ideas", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  runId: integer("run_id").notNull().references(() => weeklyIdeaRuns.id, { onDelete: "cascade" }),
  weekKey: text("week_key").notNull(),
  rank: integer("rank").notNull(),
  symbol: text("symbol").notNull(),
  name: text("name").notNull(),
  close: real("close").notNull(),
  asOfDate: text("as_of_date").notNull(),
  prior52WeekHigh: real("prior_52_week_high").notNull(),
  volumeMultiple: real("volume_multiple").notNull(),
  medianDollarVolume: real("median_dollar_volume").notNull(),
  realizedVolatility: real("realized_volatility").notNull(),
  setup: text("setup", { enum: ["breakout", "trend_pullback", "momentum_leader"] }).notNull().default("breakout"),
  setupJson: text("setup_json").notNull().default("{}"),
  historyJson: text("history_json"),
  benchmarkJson: text("benchmark_json"),
  sourceUrl: text("source_url"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  weekSymbolUnique: uniqueIndex("weekly_ideas_week_symbol_unique").on(table.weekKey, table.symbol),
  runRankIdx: index("weekly_ideas_run_rank_idx").on(table.runId, table.rank),
}));
